build.gradle: upgrade monocle dependency to jdk-11+26
The current monocle dependency we are using is 8u76-b04, which is
designed for JDK 8. Actually, running test with headless mode in JDK 11
gives the error below:

java.lang.RuntimeException
    Caused by: java.lang.RuntimeException
        Caused by: java.lang.NoClassDefFoundError
            Caused by: java.lang.ClassNotFoundException

The support for JDK 11 of monocle is jdk-11+26. [1]

As we are planning to use JDK 11+ as our supported language, let’s
upgrade the monocle dependency to the version jdk-11+26 to solve the
problem.

[1]https://github.com/TestFX/Monocle