TestUtil#assertThrows(...): support checked exceptions
TestUtil#assertThrows(...) doesn't support functions which throw checked
exceptions. For example,

    TestUtil.assertThrows(IllegalValueException.class, () -> { throw new IllegalValueException(""); });

would not compile, with the compiler complaining with:

    error: unreported exception IllegalValueException; must be caught or declared to be thrown

This is because assertThrows(...) takes in a Runnable, whose run()
method does not have `throws Exception` declared.

java.util.concurrent.Callable<V>, on the other hand, looks like what we
want, as it is a functional interface whose call() method has
`throws Exception` declared. Unfortunately, due to how Java's generics
work, call() MUST return a value. This means we will need to tack on a
`return null` at the end of our lambda bodies, which is too verbose. Not
good.

As such, let's define our own `VoidCallable` interface, and modify
assertThrows(...) to take it. Like Callable<V>, VoidCallable#call method
has `throws Exceptions` declared, so our lambdas passed to
assertThrows(...) can throw checked exceptions.  Unlike Callable<V>, its
call() method doesn't need to return a return value, allowing us to
write succinct lambda expressions to pass to assertThrows(...).