build.gradle: upgrade TestFX to 4.0.7-alpha
TestFX 4.0.7-alpha has been released. Besides being the latest and
greatest version, 4.0.7-alpha also contains a proper working headless
mode for Linux.

Without this upgrade, attempting to run `./gradlew headless guiTests` on
Linux would result with the GUI tests failing with the following
exception:

        java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""

            Caused by:
            java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""

                Caused by:
                java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""

Let's upgrade TestFX to 4.0.7-alpha to have happy Linux developers.

This working headless mode was also present in the 4.0.6-alpha, but we
couldn't upgrade to it as it broke our gui tests. (See e1eafd1 ([#353]
All gui tests are failing  (#354), 2017-03-23))

Furthermore, since headless mode now works on Linux, our Travis CI
builds do not need to run xvfb any more. As such, let's remove its usage
from .travis.yml.