build.gradle: upgrade testFX dependency to 4.0.15-alpha
The current testFx dependency we are using is 4.0.12-alpha, which gives
the error below when testing with JDK 11:

java.lang.RuntimeException
   Caused by: java.lang.NoSuchMethodError

TestFX adds support for JDK 11 since version 4.0.14-alpha.[1]

As we are planning to use JDK 11+ as our supported language, let’s
upgrade the testFX dependency to its latest stable version 4.0.15-alpha
to solve the problem.

[1]https://github.com/TestFX/TestFX/issues/640